server.port=8080
spring.application.name=campus-taskboard-api
logging.level.edu.brooklyn.cisc3130.taskboard=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
spring.datasource.url=jdbc:h2:mem:taskboarddb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false